<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1677763437339' stop='1677763497387'>
    <name>When test is too long</name>
    <title>When test is too long</title>
    <test-cases>
        <test-case start='1677763437339' status='broken' stop='1677763497386'>
            <name>This test has been executed for 150 seconds</name>
            <title>This test has been executed for 150 seconds</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-1'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-110.0.5481.100'/>
            </parameters>
            <steps/>
            <attachments/>
            <failure>
                <message>Timeout of 60000ms exceeded. The execution in the test "When test is too long This test has been executed for 150 seconds" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/node/tests/test/session.spec.ts)</message>
                <stack-trace>Error: Timeout of 60000ms exceeded. The execution in the test "When test is too long This test has been executed for 150 seconds" took too long. Try to reduce the run time or increase your timeout for test specs (https://webdriver.io/docs/timeouts). (/home/node/tests/test/session.spec.ts)
                    at createTimeoutError (/home/node/tests/node_modules/mocha/lib/errors.js:498:15)
                    at Test.Runnable._timeoutError (/home/node/tests/node_modules/mocha/lib/runnable.js:431:10)
                    at Timeout.&lt;anonymous> (/home/node/tests/node_modules/mocha/lib/runnable.js:246:24)
                    at listOnTimeout (node:internal/timers:557:17)
                    at processTimers (node:internal/timers:500:7)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>